ALTER TABLE USERS
  ADD LOGIN VARCHAR(128) NOT NULL DEFAULT '';

UPDATE USERS
SET LOGIN = NAME
WHERE LOGIN = '';

ALTER TABLE SUBMISSIONS
  ADD PROGRAMMING_LANGUAGE_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE SUBMISSIONS
  ADD CONSTRAINT FK_SUBMISSIONS_PROGRAMMING_LANGUAGES FOREIGN KEY (PROGRAMMING_LANGUAGE_ID) REFERENCES PROGRAMMING_LANGUAGES (ID);

